##############################################################################
#
# Hardware Configuration
#
# Purpose
# -------
# Auto-generated module description.
#
##############################################################################

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/9630c2bf-6d1f-4c5e-acdc-386bc054712c";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/9630c2bf-6d1f-4c5e-acdc-386bc054712c";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/9630c2bf-6d1f-4c5e-acdc-386bc054712c";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/C0A3-6F5B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Dedicated btrfs subvolume for the Firefox profile. Kept as a SIBLING of
  # the home subvolume so logged-in sessions/cookies survive even if /home is
  # wiped on reinstall. One-time creation (run on the live host):
  #   sudo mount /dev/disk/by-uuid/9630c2bf-6d1f-4c5e-acdc-386bc054712c /mnt/btrfs
  #   sudo btrfs subvolume create /mnt/btrfs/firefox-ivali
  #   sudo umount /mnt/btrfs
  fileSystems."/home/ivali/.mozilla/firefox/ivali" =
    {
      device = "/dev/disk/by-uuid/9630c2bf-6d1f-4c5e-acdc-386bc054712c";
      fsType = "btrfs";
      options = [ "subvol=firefox-ivali" "compress-force=zstd:3" "noatime" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/e6685d2c-1195-45bf-adfd-7c0470156d2a"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
