package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/willisivali/nixos-infrastructure/internal/app"
	"github.com/willisivali/nixos-infrastructure/internal/repository"
	"github.com/willisivali/nixos-infrastructure/internal/terminal"
)

func CmdDocs(a *app.App) *cobra.Command {
	return &cobra.Command{
		Use:   "docs [module]",
		Short: "Generate project documentation",
		Long: `Generate Markdown documentation from module doc headers.
With a module argument, show docs for that specific module.
Without arguments, generate a full project DOCS.md file.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if !a.RequireRepo() {
				return nil
			}
			if err := a.EnsureScanned(); err != nil {
				return err
			}

			t := a.Term
			r := a.Repo

			fmt.Println()
			fmt.Println(t.Section("Documentation"))
			fmt.Println()

			if len(args) > 0 {
				mod, info, ok := r.FindModule(args[0])
				if !ok {
					fmt.Println("  " + t.Warn("Module not found: "+args[0]))
					fmt.Println()
					return nil
				}
				fmt.Println("  " + t.Bold(mod.RelPath))
				fmt.Println()
				if info != nil && info.DocHeader != "" {
					fmt.Println("  " + info.DocHeader)
					fmt.Println()
				} else {
					fmt.Println("  " + t.Dim("(no documentation header)"))
					fmt.Println()
				}
				return nil
			}

			return writeDocs(t, r)
		},
	}
}

type modDoc struct {
	path    string
	header  string
	purpose string
}

func writeDocs(t *terminal.Terminal, r *repository.Repository) error {
	var docs []modDoc
	for _, m := range r.Result.AllModules {
		if info, ok := r.Parsed[m.Path]; ok {
			if info.DocHeader != "" || info.Purpose != "" {
				docs = append(docs, modDoc{
					path:    m.RelPath,
					header:  info.DocHeader,
					purpose: info.Purpose,
				})
			}
		}
	}

	if len(docs) == 0 {
		fmt.Println("  " + t.Dim("No documented modules found."))
		fmt.Println()
		return nil
	}

	var b strings.Builder
	b.WriteString("# Module Documentation\n\n")
	b.WriteString(fmt.Sprintf("_Generated by ivali docs — %d documented modules_\n\n", len(docs)))

	for _, d := range docs {
		b.WriteString(fmt.Sprintf("## %s\n\n", d.path))
		if d.header != "" {
			b.WriteString(d.header + "\n\n")
		}
		if d.purpose != "" {
			b.WriteString("**Purpose:** " + d.purpose + "\n\n")
		}
	}

	docPath := filepath.Join(r.Root, "DOCS.md")
	if err := os.WriteFile(docPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write docs: %w", err)
	}

	fmt.Printf("  %s %s\n", t.Good("✓"), t.Dim("Generated "+docPath))
	fmt.Println()
	return nil
}

