package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/willisivali/nixos-infrastructure/internal/app"
	"github.com/willisivali/nixos-infrastructure/internal/repository"
	"github.com/willisivali/nixos-infrastructure/internal/scanner"
	"github.com/willisivali/nixos-infrastructure/internal/terminal"
)

func CmdDocs(a *app.App) *cobra.Command {
	var generateCodex bool

	cmd := &cobra.Command{
		Use:   "docs [module]",
		Short: "Generate project documentation",
		Long: `Generate Markdown documentation from module doc headers.
With a module argument, show docs for that specific module.
Without arguments, generate a full project DOCS.md file.

Use --codex to also generate opencode/modules.md catalog.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if !a.RequireRepo() {
				return nil
			}
			if err := a.EnsureScanned(); err != nil {
				return err
			}

			t := a.Term
			r := a.Repo

			fmt.Println()
			fmt.Println(t.Section("Documentation"))
			fmt.Println()

			if len(args) > 0 {
				mod, info, ok := r.FindModule(args[0])
				if !ok {
					fmt.Println("  " + t.Warn("Module not found: "+args[0]))
					fmt.Println()
					return nil
				}
				fmt.Println("  " + t.Bold(mod.RelPath))
				fmt.Println()
				if info != nil && info.DocHeader != "" {
					fmt.Println("  " + info.DocHeader)
					fmt.Println()
				} else {
					fmt.Println("  " + t.Dim("(no documentation header)"))
					fmt.Println()
				}
				return nil
			}

			if err := writeDocs(t, r); err != nil {
				return err
			}

			if generateCodex {
				return writeCodexModules(t, r)
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&generateCodex, "codex", false, "Also generate opencode/modules.md catalog")
	return cmd
}

type modDoc struct {
	path    string
	header  string
	purpose string
}

func writeDocs(t *terminal.Terminal, r *repository.Repository) error {
	var docs []modDoc
	for _, m := range r.Result.AllModules {
		if info, ok := r.Parsed[m.Path]; ok {
			if info.DocHeader != "" || info.Purpose != "" {
				docs = append(docs, modDoc{
					path:    m.RelPath,
					header:  info.DocHeader,
					purpose: info.Purpose,
				})
			}
		}
	}

	if len(docs) == 0 {
		fmt.Println("  " + t.Dim("No documented modules found."))
		fmt.Println()
		return nil
	}

	var b strings.Builder
	b.WriteString("# Module Documentation\n\n")
	b.WriteString(fmt.Sprintf("_Generated by ivali docs — %d documented modules_\n\n", len(docs)))

	for _, d := range docs {
		b.WriteString(fmt.Sprintf("## %s\n\n", d.path))
		if d.header != "" {
			b.WriteString(d.header + "\n\n")
		}
		if d.purpose != "" {
			b.WriteString("**Purpose:** " + d.purpose + "\n\n")
		}
	}

	docPath := filepath.Join(r.Root, "DOCS.md")
	if err := os.WriteFile(docPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write docs: %w", err)
	}

	fmt.Printf("  %s %s\n", t.Good("✓"), t.Dim("Generated "+docPath))
	fmt.Println()
	return nil
}

func writeCodexModules(t *terminal.Terminal, r *repository.Repository) error {
	// Group modules by domain
	domains := make(map[string][]scanner.Module)
	for _, m := range r.Result.AllModules {
		parts := strings.SplitN(m.RelPath, "/", 2)
		domain := parts[0]
		domains[domain] = append(domains[domain], m)
	}

	// Sort domains
	var sortedDomains []string
	for d := range domains {
		sortedDomains = append(sortedDomains, d)
	}
	sort.Strings(sortedDomains)

	var b strings.Builder
	b.WriteString("# Module Catalog\n\n")
	b.WriteString("## NixOS Domain Modules\n\n")
	b.WriteString("| Domain | Location | Key Files |\n")
	b.WriteString("|--------|----------|-----------|\n")

	for _, domain := range sortedDomains {
		mods := domains[domain]
		// Find key files (not default.nix, not _ prefixed)
		var keyFiles []string
		for _, m := range mods {
			base := filepath.Base(m.RelPath)
			if base != "default.nix" && !strings.HasPrefix(base, "_") {
				keyFiles = append(keyFiles, base)
			}
		}
		if len(keyFiles) > 5 {
			keyFiles = keyFiles[:5]
			keyFiles = append(keyFiles, "...")
		}
		b.WriteString(fmt.Sprintf("| **%s** | `%s/` | %s |\n", domain, domain, strings.Join(keyFiles, ", ")))
	}

	b.WriteString("\n## Home Manager Modules\n\n")
	b.WriteString("| Module | Location | Purpose |\n")
	b.WriteString("|--------|----------|---------|\n")

	for _, domain := range sortedDomains {
		mods := domains[domain]
		for _, m := range mods {
			if strings.HasPrefix(m.RelPath, "home/") {
				info, ok := r.Parsed[m.Path]
				purpose := ""
				if ok && info.Purpose != "" {
					purpose = info.Purpose
				} else {
					purpose = strings.TrimSuffix(filepath.Base(m.RelPath), ".nix")
				}
				if len(purpose) > 40 {
					purpose = purpose[:37] + "..."
				}
				b.WriteString(fmt.Sprintf("| %s | `%s` | %s |\n", strings.TrimSuffix(filepath.Base(m.RelPath), ".nix"), m.RelPath, purpose))
			}
		}
	}

	docPath := filepath.Join(r.Root, "opencode", "modules.md")
	if err := os.WriteFile(docPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write codex modules: %w", err)
	}

	fmt.Printf("  %s %s\n", t.Good("✓"), t.Dim("Generated "+docPath))
	fmt.Println()
	return nil
}

