##############################################################################
#
# Prague — Host Spec
#
# Purpose
# -------
# Host spec for prague. Auto-discovered by hosts/hosts.nix aggregator.
# Generated by: scripts/install-fresh-nixos.sh
#
##############################################################################

{ lib, ... }:

{
  hostName = "prague";
  userName = "ivali";
  repoPath = "/home/ivali/nixos-infrastructure";
  tags = [ "tag:personal" ];
  tailnetDomain = "codlet-trench.ts.net";
  gitlabRunnerTags = [ "nixos" "prague" "self-hosted" ];
  sshAuthorizedKeys = [
  ];
  sopsKeyPath = "/home/ivali/.config/sops/age/keys.txt";
  features = {
    secrets = true;
    bitwarden = true;
    gitlabRunner = true;
    tailscale = true;
    tailscaleExitNode = true;
    ssh = true;
  };
  config = {
    ivali.desktop.gnome.enable = true;
    ivali.kilocode.enable = true;
    ivali.antigravity.enable = true;
  };
}
