{
  bind = [
    "SUPER, Q, exec, kitty"
    "SUPER, T, exec, kitty"
    "SUPER, C, killactive,"
    "SUPER, E, exec, nautilus"
    "SUPER, B, exec, firefox"
    "SUPER, SPACE, exec, rofi -show drun"
    "SUPER, A, exec, rofi -show drun"
    "SUPER, R, exec, rofi -show drun"
    "SUPER, L, exec, hyprlock"
    "SUPER, BACKSPACE, exec, wlogout"
    "SUPER, X, exec, wlogout"
    "SUPER, N, exec, swaync-client -t -sw"
    "SUPER, W, togglefloating,"
    "SUPER, F, fullscreen, 0"
    "SUPER, P, pseudo,"
    "SUPER, J, togglesplit,"
    "SUPER, G, togglegroup,"
    "SUPER SHIFT, F, pin,"
    "SUPER, S, togglespecialworkspace,"
    "SUPER SHIFT, S, movetoworkspace, special"
    "SUPER ALT, S, movetoworkspacesilent, special"
    "SUPER, left, movefocus, l"
    "SUPER, right, movefocus, r"
    "SUPER, up, movefocus, u"
    "SUPER, down, movefocus, d"
    "SUPER, h, movefocus, l"
    "SUPER, l, movefocus, r"
    "SUPER, k, movefocus, u"
    "SUPER, j, movefocus, d"
    "SUPER CTRL, h, changegroupactive, b"
    "SUPER CTRL, l, changegroupactive, f"
    "SUPER SHIFT, left, movewindow, l"
    "SUPER SHIFT, right, movewindow, r"
    "SUPER SHIFT, up, movewindow, u"
    "SUPER SHIFT, down, movewindow, d"
    "SUPER SHIFT, h, movewindow, l"
    "SUPER SHIFT, l, movewindow, r"
    "SUPER SHIFT, k, movewindow, u"
    "SUPER SHIFT, j, movewindow, d"
    "SUPER CTRL SHIFT, left, movewindow, l"
    "SUPER CTRL SHIFT, right, movewindow, r"
    "SUPER CTRL SHIFT, up, movewindow, u"
    "SUPER CTRL SHIFT, down, movewindow, d"
    "SUPER, 1, workspace, 1"
    "SUPER, 2, workspace, 2"
    "SUPER, 3, workspace, 3"
    "SUPER, 4, workspace, 4"
    "SUPER, 5, workspace, 5"
    "SUPER, 6, workspace, 6"
    "SUPER, 7, workspace, 7"
    "SUPER, 8, workspace, 8"
    "SUPER, 9, workspace, 9"
    "SUPER, 0, workspace, 10"
    "SUPER SHIFT, 1, movetoworkspace, 1"
    "SUPER SHIFT, 2, movetoworkspace, 2"
    "SUPER SHIFT, 3, movetoworkspace, 3"
    "SUPER SHIFT, 4, movetoworkspace, 4"
    "SUPER SHIFT, 5, movetoworkspace, 5"
    "SUPER SHIFT, 6, movetoworkspace, 6"
    "SUPER SHIFT, 7, movetoworkspace, 7"
    "SUPER SHIFT, 8, movetoworkspace, 8"
    "SUPER SHIFT, 9, movetoworkspace, 9"
    "SUPER SHIFT, 0, movetoworkspace, 10"
    "SUPER ALT, 1, movetoworkspacesilent, 1"
    "SUPER ALT, 2, movetoworkspacesilent, 2"
    "SUPER ALT, 3, movetoworkspacesilent, 3"
    "SUPER ALT, 4, movetoworkspacesilent, 4"
    "SUPER ALT, 5, movetoworkspacesilent, 5"
    "SUPER ALT, 6, movetoworkspacesilent, 6"
    "SUPER ALT, 7, movetoworkspacesilent, 7"
    "SUPER ALT, 8, movetoworkspacesilent, 8"
    "SUPER ALT, 9, movetoworkspacesilent, 9"
    "SUPER ALT, 0, movetoworkspacesilent, 10"
    "SUPER CTRL, Right, workspace, e+1"
    "SUPER CTRL, Left, workspace, e-1"
    "SUPER CTRL, Down, workspace, emptym"
  ];

  binde = [
    ", XF86AudioRaiseVolume, exec, pamixer -i 5"
    ", XF86AudioLowerVolume, exec, pamixer -d 5"
    ", F12, exec, pamixer -i 5"
    ", F11, exec, pamixer -d 5"
    ", XF86MonBrightnessUp, exec, brightnessctl set 5%+"
    ", XF86MonBrightnessDown, exec, brightnessctl set 5%-"
  ];

  bindl = [
    ", XF86AudioMute, exec, pamixer -t"
    ", XF86AudioMicMute, exec, pamixer -t -i 1"
    ", F10, exec, pamixer -t"
    ", XF86AudioPlay, exec, playerctl play-pause"
    ", XF86AudioNext, exec, playerctl next"
    ", XF86AudioPrev, exec, playerctl previous"
  ];

  bindm = [
    "SUPER, mouse:272, movewindow"
    "SUPER, mouse:273, resizewindow"
  ];
}
