package template

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type HostSpec struct {
	HostName           string
	UserName           string
	RepoPath           string
	Tags               []string
	TailnetDomain      string
	GitLabRunnerTags   []string
	SSHAuthorizedKeys  []string
	Features           map[string]bool
	Config             map[string]interface{}
}

func (g *Generator) HostConfig(spec HostSpec, force bool) ([]FileSpec, error) {
	spec.HostName = sanitizeName(spec.HostName)
	hostDir := filepath.Join("hosts", spec.HostName)

	// Check if host directory exists
	if !force {
		_, err := os.Stat(filepath.Join(g.Root, hostDir))
		if err == nil {
			return nil, fmt.Errorf("host %s already exists (use --force to overwrite)", spec.HostName)
		}
	}

	var files []FileSpec

	// 1. Host configuration file (hosts/<name>.nix)
	files = append(files, FileSpec{
		Path:    filepath.Join(hostDir, spec.HostName+".nix"),
		Content: g.hostConfigNix(spec),
	})

	// 2. Hardware configuration placeholder (hosts/<name>/hardware-configuration.nix)
	// This will be generated by nixos-generate-config
	files = append(files, FileSpec{
		Path: filepath.Join(hostDir, "hardware-configuration.nix"),
		Content: `# Hardware Configuration for ` + spec.HostName + `
#
# Generated by: nixos-generate-config --show-hardware-config
# DO NOT EDIT - this file will be regenerated on hardware changes

{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
}
`,
	})

	// 3. Secrets file template (secrets/hosts/<name>.yaml) - placeholder
	files = append(files, FileSpec{
		Path: filepath.Join("secrets", "hosts", spec.HostName+".yaml"),
		Content: `# SOPS secrets for ` + spec.HostName + `
#
# Encrypt with: sops --encrypt --age <age-public-key> secrets/hosts/` + spec.HostName + `.yaml
#
# Example structure:
# ssh_authorized_keys:
#   - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... user@device"
# tailscale_authkey: "tskey-auth-..."
# gitlab_runner_token: "glrt-..."
`,
	})

	return files, nil
}

func (g *Generator) hostConfigNix(spec HostSpec) string {
	var b strings.Builder

	b.WriteString("##############################################################################\n")
	b.WriteString("#\n")
	b.WriteString("# Host Configuration — " + spec.HostName + "\n")
	b.WriteString("#\n")
	b.WriteString("# Purpose\n")
	b.WriteString("# -------\n")
	b.WriteString("# Host-specific configuration for " + spec.HostName + " laptop.\n")
	b.WriteString("# Generated by: ivali bootstrap host " + spec.HostName + "\n")
	b.WriteString("#\n")
	b.WriteString("# Ownership\n")
	b.WriteString("# ---------\n")
	b.WriteString("# This file is managed by ivali bootstrap. For structural changes,\n")
	b.WriteString("# modify lib/host-templates/laptop.nix and regenerate.\n")
	b.WriteString("#\n")
	b.WriteString("##############################################################################\n")
	b.WriteString("\n")
	b.WriteString("{ config, lib, pkgs, hostSpec, hostName, defaultUsername, gitlabUrl, ... }:\n")
	b.WriteString("\n")
	b.WriteString("let\n")
	b.WriteString("  userName = hostSpec.userName or defaultUsername;\n")
	b.WriteString("\n")
	b.WriteString("  # Build effective Tailscale tags\n")
	b.WriteString("  tailscaleTags = hostSpec.tags\n")
	b.WriteString("    ++ lib.optional (hostSpec.features.tailscaleExitNode && !(builtins.elem \"tag:exit-node\" hostSpec.tags))\n")
	b.WriteString("      \"tag:exit-node\";\n")
	b.WriteString("\n")
	b.WriteString("in\n")
	b.WriteString("{\n")
	b.WriteString("  ############################################################################\n")
	b.WriteString("  # IMPORTS\n")
	b.WriteString("  ############################################################################\n")
	b.WriteString("  imports = [\n")
	b.WriteString("    ./hardware-configuration.nix\n")
	b.WriteString("    ./" + spec.HostName + ".nix\n")
	b.WriteString("  ];\n")
	b.WriteString("\n")
	b.WriteString("  ############################################################################\n")
	b.WriteString("  # SYSTEM IDENTITY\n")
	b.WriteString("  ############################################################################\n")
	b.WriteString("  networking.hostName = hostName;\n")
	b.WriteString("\n")
	b.WriteString("  ############################################################################\n")
	b.WriteString("  # USER ACCOUNT\n")
	b.WriteString("  ############################################################################\n")
	b.WriteString("  users.users.${userName} = {\n")
	b.WriteString("    isNormalUser = true;\n")
	b.WriteString("    description = \"Primary user\";\n")
	b.WriteString("    extraGroups = [ \"wheel\" \"networkmanager\" \"docker\" \"systemd-journal\" \"flatpak\" ];\n")
	b.WriteString("    shell = config.programs.zsh.package.path + \"/bin/zsh\";\n")
	b.WriteString("    home = \"/home/${userName}\";\n")
	b.WriteString("    createHome = true;\n")
	b.WriteString("    useDefaultShell = true;\n")
	b.WriteString("  };\n")
	b.WriteString("\n")
	b.WriteString("  systemd.tmpfiles.rules = [\n")
	b.WriteString("    \"d /home/${userName} 0755 ${userName} ${userName} -\"\n")
	b.WriteString("  ];\n")
	b.WriteString("\n")
	b.WriteString("  ############################################################################\n")
	b.WriteString("  # SUDO CONFIGURATION\n")
	b.WriteString("  ############################################################################\n")
	b.WriteString("  security.sudo.extraRules = [\n")

	// GitLab runner sudo rule
	if spec.Features["gitlab-runner"] {
		b.WriteString(`    # GitLab Runner needs systemctl for deployments
    {
      users = [ "gitlab-runner" ];
      commands = [
        {
          command = "/run/current-system/sw/bin/systemctl";
          options = [ "NOPASSWD" ];
        }
      ];
    }
`)
	}

	// Primary user sudo rule
	b.WriteString("    # Primary user gets full sudo\n")
	b.WriteString("    {\n")
	b.WriteString("      users = [ \"" + spec.UserName + "\" ];\n")
	b.WriteString("      commands = [\n")
	b.WriteString("        {\n")
	b.WriteString("          command = \"ALL\";\n")
	b.WriteString("          options = [ \"NOPASSWD\" ];\n")
	b.WriteString("        }\n")
	b.WriteString("      ];\n")
	b.WriteString("    }\n")

	b.WriteString(`  ];

  ############################################################################
  # GIT CONFIGURATION (system-wide for root/CI access)
  ############################################################################
  environment.etc."gitconfig".text = ''
    [safe]
      directory = ` + spec.RepoPath + `
  '';

`)

	// SOPS secrets
	if spec.Features["secrets"] {
		b.WriteString(`  ############################################################################
  # SOPS SECRETS
  ############################################################################
  config.ivali.secrets.enable = true;

  sops = {
    defaultSopsFile = ../../secrets/tailscale.yaml;
    secrets = {
      tailscale_authkey = {
        sopsFile = ../../secrets/tailscale.yaml;
      };
      grafana_secret_key = {
        sopsFile = ../../secrets/tailscale.yaml;
      };
      gitlab-runner-token = {
        sopsFile = ../../secrets/gitlab-runner.yaml;
      };
      telegram_bot_token = {
        sopsFile = ../../secrets/telegram.yaml;
      };
      telegram_chat_id = {
        sopsFile = ../../secrets/telegram.yaml;
      };
      notify_email = {
        sopsFile = ../../secrets/telegram.yaml;
      };
      gitlab_token = {
        sopsFile = ../../secrets/gitlab.yaml;
      };
      # Host-specific secrets
      ssh_authorized_keys = {
        sopsFile = ../../secrets/hosts/` + spec.HostName + `.yaml;
      };
    };
  };

`)
	}

	// GitLab Runner
	if spec.Features["gitlab-runner"] && spec.Features["secrets"] {
		runnerTags := strings.Join(spec.GitLabRunnerTags, `" "`)
		b.WriteString("  ############################################################################\n")
		b.WriteString("  # GITLAB RUNNER\n")
		b.WriteString("  ############################################################################\n")
		b.WriteString("  fleet.gitlabRunner = {\n")
		b.WriteString("    enable = true;\n")
		b.WriteString("    tokenFile = config.sops.secrets.gitlab-runner-token.path;\n")
		b.WriteString("    tags = [ \"" + runnerTags + "\" ];\n")
		b.WriteString("    concurrent = 1;\n")
		b.WriteString("  };\n")
		b.WriteString("\n")
	}

	// Telegram Bot
	if spec.Features["bot"] && spec.Features["secrets"] {
		b.WriteString("  ############################################################################\n")
		b.WriteString("  # TELEGRAM BOT CONTROL PLANE\n")
		b.WriteString("  ############################################################################\n")
		b.WriteString("  fleet.bot = {\n")
		b.WriteString("    enable = true;\n")
		b.WriteString("    gitlabUrl = gitlabUrl;\n")
		b.WriteString("    defaultUser = \"" + spec.UserName + "\";\n")
		b.WriteString("  };\n")
		b.WriteString("\n")
	}

	// Tailscale
	if spec.Features["tailscale"] {
		tagsStr := strings.Join(spec.Tags, `", "`)
		exitNode := "false"
		if spec.Features["tailscale-exit-node"] {
			exitNode = "true"
		}
		tailnetDomain := "null"
		if spec.TailnetDomain != "" {
			tailnetDomain = `"` + spec.TailnetDomain + `"`
		}
		authKeyFile := "null"
		if spec.Features["secrets"] {
			authKeyFile = "config.sops.secrets.tailscale_authkey.path"
		}

		b.WriteString("  ############################################################################\n")
		b.WriteString("  # TAILSCALE ZERO-TRUST NETWORKING\n")
		b.WriteString("  ############################################################################\n")
		b.WriteString("  ivali.tailscale = {\n")
		b.WriteString("    enable = true;\n")
		b.WriteString("    authKeyFile = " + authKeyFile + ";\n")
		b.WriteString("    tags = [ \"" + tagsStr + "\" ];\n")
		b.WriteString("    advertiseExitNode = " + exitNode + ";\n")
		b.WriteString("    acceptDns = false;\n")
		b.WriteString("    acceptRoutes = false;\n")
		b.WriteString("    tailnetDomain = " + tailnetDomain + ";\n")
		b.WriteString("  };\n")
		b.WriteString("\n")
	}

	// SSH
	if spec.Features["ssh"] {
		keys := strings.Join(spec.SSHAuthorizedKeys, `", "` + "\n        ")
		if keys != "" {
			keys = "\n        " + keys + "\n      "
		}
		b.WriteString("  ############################################################################\n")
		b.WriteString("  # SSH DAEMON (Tailscale-only access)\n")
		b.WriteString("  ############################################################################\n")
		b.WriteString("  ivali.ssh = {\n")
		b.WriteString("    enable = true;\n")
		b.WriteString("    allowedUsers = [ \"" + spec.UserName + "\" ];\n")
		b.WriteString("    authorizedKeys = [ " + keys + " ];\n")
		b.WriteString("    tailscaleOnly = true;\n")
		b.WriteString("  };\n")
		b.WriteString("\n")
	}

	b.WriteString(`}
`)

	return b.String()
}