package template

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type HostSpec struct {
	HostName           string
	UserName           string
	RepoPath           string
	Tags               []string
	TailnetDomain      string
	GitLabRunnerTags   []string
	SSHAuthorizedKeys  []string
	Features           map[string]bool
	Config             map[string]interface{}
}

func (g *Generator) HostConfig(spec HostSpec, force bool) ([]FileSpec, error) {
	spec.HostName = sanitizeName(spec.HostName)
	hostDir := filepath.Join("hosts", spec.HostName)

	// Check if host directory exists
	if !force {
		_, err := os.Stat(filepath.Join(g.Root, hostDir))
		if err == nil {
			return nil, fmt.Errorf("host %s already exists (use --force to overwrite)", spec.HostName)
		}
	}

	var files []FileSpec

	// 1. Host configuration file (hosts/<name>.nix)
	files = append(files, FileSpec{
		Path:    filepath.Join(hostDir, spec.HostName+".nix"),
		Content: g.hostConfigNix(spec),
	})

	// 2. Hardware configuration placeholder (hosts/<name>/hardware-configuration.nix)
	// This will be generated by nixos-generate-config
	files = append(files, FileSpec{
		Path: filepath.Join(hostDir, "hardware-configuration.nix"),
		Content: `# Hardware Configuration for ` + spec.HostName + `
#
# Generated by: nixos-generate-config --show-hardware-config
# DO NOT EDIT - this file will be regenerated on hardware changes

{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
}
`,
	})

	// 3. Secrets file template (secrets/hosts/<name>.yaml) - placeholder
	files = append(files, FileSpec{
		Path: filepath.Join("secrets", "hosts", spec.HostName+".yaml"),
		Content: `# SOPS secrets for ` + spec.HostName + `
#
# Encrypt with: sops --encrypt --age <age-public-key> secrets/hosts/` + spec.HostName + `.yaml
#
# Example structure:
# ssh_authorized_keys:
#   - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... user@device"
# tailscale_authkey: "tskey-auth-..."
# gitlab_runner_token: "glrt-..."
`,
	})

	return files, nil
}

func (g *Generator) hostConfigNix(spec HostSpec) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf(`##############################################################################
#
# Host Configuration — %s
#
# Purpose
# -------
# Host-specific configuration for %s laptop.
# Generated by: ivali bootstrap host %s
#
# Ownership
# ---------
# This file is managed by ivali bootstrap. For structural changes,
# modify lib/host-templates/laptop.nix and regenerate.
#
##############################################################################

{ config, lib, pkgs, hostSpec, hostName, defaultUsername, gitlabUrl, ... }:

let
  userName = hostSpec.userName or defaultUsername;

  # Build effective Tailscale tags
  tailscaleTags = hostSpec.tags
    ++ lib.optional (hostSpec.features.tailscaleExitNode && !(builtins.elem "tag:exit-node" hostSpec.tags))
      "tag:exit-node";

in
{
  ############################################################################
  # IMPORTS
  ############################################################################
  imports = [
    ./hardware-configuration.nix
    ./` + spec.HostName + `.nix
  ];

  ############################################################################
  # SYSTEM IDENTITY
  ############################################################################
  networking.hostName = hostName;

  ############################################################################
  # USER ACCOUNT
  ############################################################################
  users.users.${userName} = {
    isNormalUser = true;
    description = "Primary user";
    extraGroups = [ "wheel" "networkmanager" "docker" "systemd-journal" "flatpak" ];
    shell = config.programs.zsh.package.path + "/bin/zsh";
    home = "/home/${userName}";
    createHome = true;
    useDefaultShell = true;
  };

  systemd.tmpfiles.rules = [
    "d /home/${userName} 0755 ${userName} ${userName} -"
  ];

  ############################################################################
  # SUDO CONFIGURATION
  ############################################################################
  security.sudo.extraRules = [
`))

	// GitLab runner sudo rule
	if spec.Features["gitlab-runner"] {
		b.WriteString(`    # GitLab Runner needs systemctl for deployments
    {
      users = [ "gitlab-runner" ];
      commands = [
        {
          command = "/run/current-system/sw/bin/systemctl";
          options = [ "NOPASSWD" ];
        }
      ];
    }
`)
	}

	// Primary user sudo rule
	b.WriteString(fmt.Sprintf(`    # Primary user gets full sudo
    {
      users = [ "%s" ];
      commands = [
        {
          command = "ALL";
          options = [ "NOPASSWD" ];
        }
      ];
    }
`, spec.UserName))

	b.WriteString(`  ];

  ############################################################################
  # GIT CONFIGURATION (system-wide for root/CI access)
  ############################################################################
  environment.etc."gitconfig".text = ''
    [safe]
      directory = ` + spec.RepoPath + `
  '';

`)

	// SOPS secrets
	if spec.Features["secrets"] {
		b.WriteString(`  ############################################################################
  # SOPS SECRETS
  ############################################################################
  config.ivali.secrets.enable = true;

  sops = {
    defaultSopsFile = ../../secrets/tailscale.yaml;
    secrets = {
      tailscale_authkey = {
        sopsFile = ../../secrets/tailscale.yaml;
      };
      grafana_secret_key = {
        sopsFile = ../../secrets/tailscale.yaml;
      };
      gitlab-runner-token = {
        sopsFile = ../../secrets/gitlab-runner.yaml;
      };
      telegram_bot_token = {
        sopsFile = ../../secrets/telegram.yaml;
      };
      telegram_chat_id = {
        sopsFile = ../../secrets/telegram.yaml;
      };
      notify_email = {
        sopsFile = ../../secrets/telegram.yaml;
      };
      gitlab_token = {
        sopsFile = ../../secrets/gitlab.yaml;
      };
      # Host-specific secrets
      ssh_authorized_keys = {
        sopsFile = ../../secrets/hosts/` + spec.HostName + `.yaml;
      };
    };
  };

`)
	}

	// GitLab Runner
	if spec.Features["gitlab-runner"] && spec.Features["secrets"] {
		runnerTags := strings.Join(spec.GitLabRunnerTags, `" "`)
		b.WriteString(fmt.Sprintf(`  ############################################################################
  # GITLAB RUNNER
  ############################################################################
  fleet.gitlabRunner = {
    enable = true;
    tokenFile = config.sops.secrets.gitlab-runner-token.path;
    tags = [ "%s" ];
    concurrent = 1;
  };

`, runnerTags))
	}

	// Telegram Bot
	if spec.Features["bot"] && spec.Features["secrets"] {
		b.WriteString(fmt.Sprintf(`  ############################################################################
  # TELEGRAM BOT CONTROL PLANE
  ############################################################################
  fleet.bot = {
    enable = true;
    gitlabUrl = gitlabUrl;
    defaultUser = "%s";
  };

`, spec.UserName))
	}

	// Tailscale
	if spec.Features["tailscale"] {
		tagsStr := strings.Join(spec.Tags, `", "`)
		exitNode := "false"
		if spec.Features["tailscale-exit-node"] {
			exitNode = "true"
		}
		tailnetDomain := "null"
		if spec.TailnetDomain != "" {
			tailnetDomain = `"` + spec.TailnetDomain + `"`
		}
		authKeyFile := "null"
		if spec.Features["secrets"] {
			authKeyFile = "config.sops.secrets.tailscale_authkey.path"
		}

		b.WriteString(fmt.Sprintf(`  ############################################################################
  # TAILSCALE ZERO-TRUST NETWORKING
  ############################################################################
  ivali.tailscale = {
    enable = true;
    authKeyFile = %s;
    tags = [ "%s" ];
    advertiseExitNode = %s;
    acceptDns = false;
    acceptRoutes = false;
    tailnetDomain = %s;
  };

`, authKeyFile, tagsStr, exitNode, tailnetDomain))
	}

	// SSH
	if spec.Features["ssh"] {
		keys := strings.Join(spec.SSHAuthorizedKeys, `", "` + "\n        ")
		if keys != "" {
			keys = "\n        " + keys + "\n      "
		}
		b.WriteString(fmt.Sprintf(`  ############################################################################
  # SSH DAEMON (Tailscale-only access)
  ############################################################################
  ivali.ssh = {
    enable = true;
    allowedUsers = [ "%s" ];
    authorizedKeys = [ %s ];
    tailscaleOnly = true;
  };

`, spec.UserName, keys))
	}

	b.WriteString(`}
`)

	return b.String()
}