package template

import (
	"fmt"
	"os"
	"path/filepath"
)

type HostSpec struct {
	HostName          string
	UserName          string
	RepoPath          string
	Tags              []string
	TailnetDomain     string
	GitLabRunnerTags  []string
	SSHAuthorizedKeys []string
	Features          map[string]bool
	Config            map[string]interface{}
}

func (g *Generator) HostConfig(spec HostSpec, force bool) ([]FileSpec, error) {
	spec.HostName = sanitizeName(spec.HostName)
	hostDir := filepath.Join("hosts", spec.HostName)

	// Check if host directory exists
	if !force {
		_, err := os.Stat(filepath.Join(g.Root, hostDir))
		if err == nil {
			return nil, fmt.Errorf("host %s already exists (use --force to overwrite)", spec.HostName)
		}
	}

	var files []FileSpec

	// 1. Hardware configuration (hosts/<name>/hardware-configuration.nix)
	// This will be generated by nixos-generate-config
	files = append(files, FileSpec{
		Path: filepath.Join(hostDir, "hardware-configuration.nix"),
		Content: `# Hardware Configuration for ` + spec.HostName + `
#
# Generated by: nixos-generate-config --show-hardware-config
# DO NOT EDIT - this file will be regenerated on hardware changes

{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
}
`,
	})

	// 2. Secrets file template (secrets/hosts/<name>.yaml) - placeholder
	files = append(files, FileSpec{
		Path: filepath.Join("secrets", "hosts", spec.HostName+".yaml"),
		Content: `# SOPS secrets for ` + spec.HostName + `
#
# Encrypt with: sops --encrypt --age <age-public-key> secrets/hosts/` + spec.HostName + `.yaml
#
# Example structure:
# ssh_authorized_keys:
#   - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... user@device"
# tailscale_authkey: "tskey-auth-..."
# gitlab_runner_token: "glrt-..."
`,
	})

	return files, nil
}
